import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage();
page.on('console', msg => console.log('CONSOLE:'+msg.text().slice(0,600)));
page.on('pageerror', err => console.log('PAGEERR:'+err.message+'\n'+(err.stack||'').slice(0,2000)));
console.log('goto start');
await page.goto('http://127.0.0.1:3002/admin/renewals?demo=1', { waitUntil: 'domcontentloaded', timeout: 15000 });
console.log('goto done load');
await new Promise(r=>setTimeout(r,5000));
const text = await page.evaluate(()=> document.body.innerText.slice(0,4000));
console.log('TEXT:'+text);
const hasRenewals = await page.evaluate(()=> !!document.body.innerHTML.includes('Renewals'));
console.log('hasRenewals:'+hasRenewals);
await browser.close();
console.log('done');
