import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage();
page.on('console', msg => console.log('CONSOLE:'+msg.text().slice(0,700)));
page.on('pageerror', err => console.log('PAGEERR:'+err.message));
console.log('goto start');
await page.goto('http://127.0.0.1:3002/admin/renewals?demo=1', { waitUntil: 'domcontentloaded', timeout: 15000 });
console.log('goto done');
await new Promise(r=>setTimeout(r,4000));
const text = await page.evaluate(()=> document.body.innerText.slice(0,5000));
console.log('TEXT:'+text.slice(0,3000));
await browser.close();
console.log('done');
