import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage();
page.on('console', msg => console.log('CONSOLE:'+msg.text().slice(0,900)));
page.on('pageerror', err => console.log('PAGEERR:'+err.message));
await page.goto('http://127.0.0.1:3002/admin/renewals?demo=1', { waitUntil: 'domcontentloaded', timeout: 15000 });
await new Promise(r=>setTimeout(r,5000));
console.log('URL after:', page.url());
console.log('SEARCH:', await page.evaluate(()=> window.location.search));
console.log('HAS_DEMO:', await page.evaluate(()=> new URLSearchParams(window.location.search).has('demo')));
console.log('TEXT:', (await page.evaluate(()=> document.body.innerText)).slice(0,3000).replace(/\s+/g,' '));
await browser.close();
